
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const POST_ADDED = 'POST_ADDED'
export const POST_UPDATED = 'POST_UPDATED'
export const POST_DELETED = 'POST_DELETED'
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY'

export const GET_COMMENTS = 'GET_COMMENTS'
export const COMMENT_ADDED = 'COMMENT_ADDED'
export const COMMENT_UPDATED = 'COMMENT_UPDATED'
export const COMMENT_DELETED = 'COMMENT_DELETED'
export const UPDATE_SORT_COMMENTS_BY = 'UPDATE_SORT_COMMENTS_BY'
